language: python
python:
  - 3.6
addons:
  postgresql: "9.4"
install: 
  - pip install -r requirements.txt 
  - pip install awscli
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_fondo_api;" -U postgres
  - psql -c "CREATE EXTENSION hstore;" -U postgres -d test_fondo_api
  - python3 manage.py makemigrations fondo_api && python3 manage.py migrate
env:
  global:
    - POSTGRES_DATABASE=test_fondo_api
    - POSTGRES_USER=postgres
    - POSTGRES_HOST=localhost
    - POSTGRES_PASSWORD=
    - POSTGRES_PORT=5432
    - DJANGO_SETTINGS_MODULE=api.settings.development
script:
  - coverage run --branch --source='.' manage.py test && coverage report -m --omit="*env*,*tests*,api/wsgi.py,fondo_api/apps.py,manage.py,*migrations*"
deploy:
  - provider: script
    script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh $TRAVIS_COMMIT i-0feb65e210a1d6181 $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: sh $TRAVIS_BUILD_DIR/scripts/trigger-deploy.sh $TRAVIS_COMMIT i-025148658658cc498 $TRAVIS_BRANCH
    skip_cleanup: true
    on:
      branch: develop
