language: python
python:
  - 3.6
install: pip install -r requirements.txt 
services:
  - postgresql
before_script:
  - psql -c "CREATE DATABASE test_fondo_api;" -U postgres
  - python3 manage.py makemigrations fondo_api && python3 manage.py migrate
env:
  matrix:
    - POSTGRES_DATABASE=test_fondo_api POSTGRES_USER=postgres POSTGRES_HOST=localhost POSTGRES_PASSWORD= POSTGRES_PORT=5432
script:
  - python3 manage.py test
