from enum import Enum

class EmailTemplate(Enum):
  USER_ACTIVATION = 1
  CHANGE_STATE_LOAN_APPROVED = 2
  CHANGE_STATE_LOAN_DENIED = 3
  POWER_APPROVED = 4
  TEST = 5
  PASSWORD_RESET = 6
  TMP = 9999