# Generated by Django 2.1.2 on 2018-11-03 18:59

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('value', models.BigIntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(0, 'NOT_PAID'), (1, 'PAID_OUT'), (2, 'EXEMPTED')], default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
                ('timelimit', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('payment', models.IntegerField(choices=[(0, 'CASH'), (1, 'BANK_ACCOUNT'), (2, 'REFINANCED')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.IntegerField(choices=[(0, 'MONTHLY'), (1, 'UNIQUE')])),
                ('comments', models.TextField(null=True)),
                ('state', models.IntegerField(choices=[(0, 'WAITING_APPROVAL'), (1, 'APPROVED'), (2, 'DENIED'), (3, 'PAID_OUT')], default=0)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=5)),
                ('refinanced_loan', models.BigIntegerField(null=True)),
                ('prev_loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fondo_api.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='LoanDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payment', models.BigIntegerField(default=0)),
                ('minimum_payment', models.BigIntegerField(default=0)),
                ('payday_limit', models.DateField()),
                ('interests', models.BigIntegerField(default=0)),
                ('capital_balance', models.BigIntegerField(default=0)),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='UserFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.BigIntegerField()),
                ('balance_contributions', models.BigIntegerField()),
                ('total_quota', models.BigIntegerField()),
                ('utilized_quota', models.BigIntegerField(default=0)),
                ('available_quota', models.BigIntegerField()),
                ('last_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('identification', models.BigIntegerField(unique=True)),
                ('role', models.IntegerField(choices=[(0, 'ADMIN'), (1, 'PRESIDENT'), (2, 'TREASURER'), (3, 'MEMBER')], default=3)),
                ('key_activation', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='userfinance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='activityuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(through='fondo_api.ActivityUser', to='fondo_api.UserProfile'),
        ),
        migrations.AddField(
            model_name='activity',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.ActivityYear'),
        ),
    ]
