# Generated by Django 2.0 on 2017-12-09 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BigIntegerField()),
                ('timelimit', models.DateTimeField()),
                ('disbursement_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee', models.IntegerField(choices=[(0, 'MONTHLY'), (1, 'UNIQUE')])),
                ('state', models.IntegerField(choices=[(0, 'WAITING_APPROVAL'), (1, 'APPROVED'), (2, 'DENIED'), (3, 'PAID_OUT')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('identification', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.IntegerField(choices=[(0, 'ADMIN'), (1, 'PRESIDENT'), (2, 'TREASURER'), (3, 'MEMBER')], default=3)),
                ('is_active', models.BooleanField(default=False)),
                ('is_authenticated', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserFinance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributions', models.BigIntegerField()),
                ('balance_contributions', models.BigIntegerField()),
                ('total_quota', models.BigIntegerField()),
                ('available_quota', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.User')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.User'),
        ),
    ]
