# Generated by Django 2.1.2 on 2018-11-02 22:26

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', django.contrib.postgres.fields.hstore.HStoreField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.UserProfile')),
            ],
        ),
    ]
