# Generated by Django 2.1.2 on 2018-11-03 19:00

from django.db import migrations

def create_user_preferences(apps, schema_editor):
    UserProfile = apps.get_model("fondo_api", "UserProfile")
    UserPreference = apps.get_model('fondo_api', "UserPreference")
    for user in UserProfile.objects.all():
        UserPreference.objects.create( user = user )

'''
## Adds user preferences to all existing users
'''
class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0002_notificationsubscriptions_userpreference'),
    ]

    operations = [
        migrations.RunPython(create_user_preferences)
    ]
