# Generated by Django 2.1.2 on 2018-11-03 19:08

from django.db import migrations

def remove_activation_keys(apps, schema_editor):
    UserProfile = apps.get_model("fondo_api", "UserProfile")
    for user in UserProfile.objects.all():
        user.key_activation = None
        user.save()

'''
## Remove activation keys to all users
'''
class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0003_auto_20181103_1400'),
    ]

    operations = [
        migrations.RunPython(remove_activation_keys)
    ]
