# Generated by Django 2.1.5 on 2019-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0004_auto_20181103_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityyear',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
