# Generated by Django 2.1.5 on 2019-02-03 16:43

from datetime import date
from django.db import migrations
from django.db.models import Q

def disabling_last_years(apps, schema_editor):
    ActivityYear = apps.get_model("fondo_api", "ActivityYear")
    current_year = date.today().year
    for activity_year in ActivityYear.objects.filter(~Q(year = current_year)):
        activity_year.enable = False
        activity_year.save()

'''
## Disable Activity Years previous to current year.
'''
class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0005_activityyear_enable'),
    ]

    operations = [
        migrations.RunPython(disabling_last_years)
    ]
