# Generated by Django 2.1.5 on 2019-06-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0006_auto_20190203_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='primary_color',
            field=models.CharField(default='#800000', max_length=15),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='secondary_color',
            field=models.CharField(default='#c83737', max_length=15),
        ),
    ]
