# Generated by Django 2.1.11 on 2019-12-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0007_auto_20190609_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='disbursement_value',
            field=models.BigIntegerField(null=True),
        ),
    ]
