# Generated by Django 2.2.10 on 2020-02-23 20:16

from django.db import migrations

def insert_proceedings(apps, schema_editor):
    File = apps.get_model("fondo_api", "File")
    files = [
        "Acta número 1",
        "Acta número 2",
        "Acta número 3",
        "Acta número 4",
        "Acta número 5",
        "Acta número 6",
        "Acta número 7",
        "Acta número 8",
        "Acta número 9",
        "Acta número 10",
        "Acta número 11",
        "Acta número 12",
        "Acta número 13",
        "Acta número 14",
        "Acta número 15"
    ]
    for filename in files:
        new_file = File(
            type = 0,
            display_name = filename
        )
        new_file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0011_file_created_at'),
    ]

    operations = [
        migrations.RunPython(insert_proceedings)
    ]
