# Generated by Django 2.2.10 on 2020-04-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0012_auto_20200223_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
