# Generated by Django 2.2.10 on 2020-04-12 15:38

from django.db import migrations

def delete_all_scheduled_tasks(apps, schema_editor):
    SchedulerTask = apps.get_model("fondo_api", "SchedulerTask")
    SchedulerTask.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0013_userprofile_birthdate'),
    ]

    operations = [
        migrations.RunPython(delete_all_scheduled_tasks)
    ]
