# Generated by Django 2.2.24 on 2021-08-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0015_schedulertask_repeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('state', models.IntegerField(choices=[(0, 'PENDING'), (1, 'APPROVED'), (2, 'REJECTED')], default=0)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_requestee', to='fondo_api.UserProfile')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_requested', to='fondo_api.UserProfile')),
            ],
        ),
    ]
