# Generated by Django 2.2.27 on 2022-02-13 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0016_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'CLOSED')], default=0)),
                ('value', models.BigIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fondo_api.UserProfile')),
            ],
        ),
    ]
