# Generated by Django 2.2.27 on 2022-03-13 17:25

from django.db import migrations

def insert_presentations(apps, schema_editor):
    File = apps.get_model("fondo_api", "File")
    files = [
        "Resultados 2012",
        "Resultados 2013",
        "Resultados 2014",
        "Resultados 2015",
        "Resultados 2016",
        "Resultados 2017",
        "Resultados 2018",
        "Resultados 2019",
        "Resultados 2020",
        "Resultados 2021",
    ]
    for filename in files:
        new_file = File(
            type = 1,
            display_name = filename
        )
        new_file.save()

class Migration(migrations.Migration):

    dependencies = [
        ('fondo_api', '0018_auto_20220313_1217'),
    ]

    operations = [
        migrations.RunPython(insert_presentations)
    ]
